# Generated by Django 5.2 on 2025-04-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('achievement_level', models.TextField()),
                ('performance_process', models.TextField()),
                ('competency', models.TextField()),
                ('teacher_comment', models.TextField()),
                ('full_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
